spring:
  application:
    name: proy-restemplate-service-client
  freemarker:
    enabled: false
  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:/templates/
    suffix: .html

eureka:
  #instance:
   # lease-renewal-interval-in-seconds: 1
   # lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
      
info:
  project:
    name: Zion API Consumer con Rest Template
    description: Proyecto que actuara cliente usando Rest Template y el servicio proy-service-oracle asi como Eureka, Zuul y Config-server.
    version: 0.0.1-SNAPSHOT
      
server:
  port: 5006