spring:
  application:
    name: proy-cassandra-service-provider
  data:
    cassandra:
      username: test
      password: test
      port: 9042
      keyspace-name: test_cassandra
      contact-points: 127.0.0.1
  freemarket:
    enabled: false
  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:/templates/
    sufix: .html
#SE RETIRA JPA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}

server:
  port: 5009
  controller.context-path: /api/point-service/v1

#SWAGGER - SE AÑADEN SETEO DE PROPIEDADES SOLO DE MAPEO REFERENCIAL, NO SON AUTOMATICOS PROPIOS DE LA LIBRERIA
application:
  swagger:
    title: Services Points
    description: Api de gestion de Puntos de Ubicacion
    version: v1
    default:
      codes: 201,400,500




