spring:
  application:
    name: proy-zuul-provider

zuul:
  routes:
    oracle:
      path: /api/base/**
      service-id: PROY-ORACLE-PROVIDER
      strip-prefix: false
      url: http://localhost:5002
      
server:
  port: 5003
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
      
