spring:
  application:
    name: proy-restemplate-service-client
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: bd_galaxy
    password: galaxy123
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari: #CONFIGURATION DE POOL DE CONEXIONES
      connection-timeout: 60000
      maximum-pool-size: 5
  freemarker:
    enabled: false
  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:/templates/
    suffix: .html

eureka:
  instance:
   lease-renewal-interval-in-seconds: 1
   lease-expiration-duration-in-seconds: 2
   metadata-map:
     instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
      
server:
  port: 5006
  controller.context-path: /restemplate/client