spring:
  application:
    name: proy-feign-service-client
  freemarker:
    enabled: false
  thymeleaf:
    enabled: true
    cache: true
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html

server:
  port: 5005
  controller.context-path: /client/feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
      
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
