spring:
  application:
    name: proy-zuul-server

zuul:
  prefix: /bcp.com.pe #PREFIJO DE CONTEXTO BASE ADICIONAL DE ZUUL Ejm: http://localhost:5000/bcp.com.pe/api/base/galaxy
  routes:
    oracle:
      path: /api/base/**
      service-id: PROY-ORACLE-PROVIDER
      strip-prefix: false
      url: http://localhost:5002
 
#hystrix:
 # command:
  #  default:
   #   execution:
    #    isolation:
     #     thread:
      #      timeoutInMilliseconds: 20000
            
#ribbon:
 # eureka:
  #  anable: true
   # ReadTimeout: 20000
    #ConnectTimeout: 2000
    
server:
  port: 5003
  
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2 #intento de conectarse cada 2 segundos
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
      
info:
  component: proy-zuul-server
      
