spring:
  application:
    name: proy-retrofit-service-client
  freemarker:
    enabled: false
  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:/templates/
    suffix: .html 
  
eureka:
  instance:
   lease-renewal-interval-in-seconds: 1
   lease-expiration-duration-in-seconds: 2
   metadata-map:
     instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
      
server:
  port: 5008
  controller.context-path: /client/retrofit

oracle:
  uri:
    provider: http://localhost:5002/