spring:
  application:
    name: proy-web-app
  datasource:
    url: jdbc:mysql://localhost:3302/bd_sofia2
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect #permite entender el mapeo de las tablas
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      #naming:
       # implicit-strategy: org.hibernate.boot.
       # physical-strategy: org.hibernate.boot.
  freemarker:
    enabled: false
  thymeleaf:
    enabled: false
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/views/ #ruteo de views
      suffix: .jsp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
server:
  port: 5020